# # This is a basic workflow to help you get started with Actions

# name: CI

# # Controls when the action will run. 
# on:
#   # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]

#   # Allows you to run this workflow manually from the Actions tab.
#   workflow_dispatch:

# # A workflow run is made up of one or more jobs that can run sequentially or in parallel
# jobs:
#   # This workflow contains a single job called "build"
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       - name: Setup Node.js environment
#         uses: actions/setup-node@v2-beta
#         with:
#           # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
#              node-version: 12
        
#       - name: creating build
#         run: 
#           npm install
#           npm build

#       - name: installing surge
#         run: npm install -g surge

#       - name: deploying on surge
#         run: surge ./build http://react-app-one-bootcamp2020.surge.sh/ --token ${{secrets.SURGE_TOKEN}} #surge ./build http://react-app-one-bootcamp2020.surge.sh/ --token ${{secrets.SURGE_TOKEN}}


name: Deploy react app to Surge

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2-beta
      with:
          node-version: 12
    
    - name: Build React App
      run: |
        npm install # Install Dependencies
        CI=false npm run build # CI=false to ignore warnings
        
    - name: Install Surge
      run: npm install -g surge
      
    - name: Deploy to Surge
      run:  surge ./build http://react-app-one-bootcamp2020.surge.sh/ --token ${{secrets.SURGE_TOKEN}}